task/urls.py
from django.urls import path

from task.views import TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView, TagListView, TagCreateView, \
    TagUpdateView, TagDeleteView, complete_task

urlpatterns = [
    path("", TaskListView.as_view(), name='task-list'),
    path("task/create", TaskCreateView.as_view(), name="task-create"),
    path("task/update/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("task/delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags", TagListView.as_view(), name='tag-list'),
    path("tags/create", TagCreateView.as_view(), name="tag-create"),
    path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
    path("task/<int:pk>/complete/", complete_task, name="task-complete"),
]
app_name = "task"

task_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("task.urls", namespace="task"))
]

task/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    done = models.BooleanField()
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["done", "-created"]

task/forms.py
from django import forms
from django.forms import DateTimeField

from task.models import Task


class TaskCreatingForm(forms.ModelForm):
    deadline = DateTimeField(input_formats=['%Y-%m-%d %H:%M'])

    class Meta:
        model = Task
        fields = "__all__"

task/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from task.forms import TaskCreatingForm
from task.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskCreatingForm
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task:task-list")


class TaskDeleteView( generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


def complete_task(request, pk):
    task = Task.objects.get(id=pk)
    if task.done:
        task.done = False
    else:
        task.done = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("task:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Task-list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}



        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">

  <li class="list-group-item"><a href="{% url 'task:task-list' %}">Home</a></li>
    <li class="list-group-item"><a href="{% url 'task:tag-list' %}">Tags</a></li>


</ul>

templates/task/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h1> Confirm deleting {{ task.name }}</h1>
    <br>
    <p>Are you sure you want to remove this task?</p>
    <form method="post" action="">
{% csrf_token %}

<input type="submit" value="Submit" class="btn btn-danger" />
    </form>
{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create" }} Tag:</h1>
    <form method="post" action="" novalidate>
{% csrf_token %}
{{ form.as_p }}

<input type="submit" value="Submit" class="btn btn-primary" />
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}

{% block content %}
    <div class="ml-3">
        <h1>Tags
            <a href="{% url "task:tag-create" %}" type="button" class="btn btn-primary">Add</a>
        </h1>


{% if tag_list %}
      <table class="table">
        <tr>
            <th>Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for tag in tag_list %}
            <tr>
                <td>
                    {{ tag.name }}
                </td>
                <td>
                    <a href="{% url "task:tag-update" pk=tag.id %}" class="btn btn-primary"> Update </a>
                </td>
                <td>
                    <a href="{% url "task:tag-delete" pk=tag.id %}" class="btn btn-danger"> Delete </a>
                </td>


          </tr>
        {% endfor %}
      </table>

    {% else %}
        <p>No tags</p>
    {% endif %}
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h1> Confirm deleting {{ task.name }}</h1>
    <br>
    <p>Are you sure you want to remove this task?</p>
    <form method="post" action="">
{% csrf_token %}

<input type="submit" value="Submit" class="btn btn-danger" />
    </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create" }} Task:</h1>
    <form method="post" action="" novalidate>
{% csrf_token %}
{{ form.as_p }}

<input type="submit" value="Submit" class="btn btn-primary" />
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block content %}
    <div class="ml-3">
        <h1>
            TO DO List
            <a href="{% url "task:task-create" %}" class="btn btn-primary float-right">Add task</a>
        </h1>

        {% for task in task_list %}

        <hr>
            <p><strong>{{ task.content }} </strong>
                {% if task.done %}
                    <strong class="text-success">Done</strong>
                    <a href="{% url "task:task-complete" pk=task.id %}" class="btn btn-secondary float-right">Undo</a>
                {% else %}
                    <strong class="text-danger">Not done</strong>
                    <a href="{% url "task:task-complete" pk=task.id %}" class="btn btn-success float-right">Complete</a>
                {% endif %}

            </p>


        <p><small>{{ task.created }}
            {% if task.deadline %}
                <text class="text-danger">deadline: {{ task.deadline }}</text>
            {% endif %}
        </small></p>
        <p class="text-muted">Tags: {% for tag in task.tags.all %} {{tag.name}}{% endfor %}</p>
        <a href="{% url "task:task-update" pk=task.id %}" type="button" class="btn btn-primary">Update</a>
        <a href="{% url "task:task-delete" pk=task.id %}" type="button" class="btn btn-danger">Delete</a>
    {% empty %}
      <p>No Task!</p>
    {% endfor %}
  </div>
{% endblock %}